meta_product_name: "HomeTog"
meta_title: "HomeTog - Let's find you the perfect photographer!"
meta_description: "A one stop app where photographers of all skill levels can list their services and realtors can find, book, and rate their performance."
meta_image: "facebook-image2.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
